spring.application.name=backbelisario
spring.datasource.url=jdbc:h2:mem:polleriadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8080
server.error.include-message=always

# JWT Configuration
app.jwt.secret=belisario-polleria-super-secret-key-256bits-secure
app.jwt.expiration=86400000
